---
# tasks file for common
- name: create devops group
  become: yes
  become_user: root
  group:
    name: devops
    state: present
    
- name: create devops user with admin privileges and assign to devops group
  become: yes
  become_user: root
  user: 
    name: "devops"
    password: "devops"
    comment: "DevOps User"
    uid: 2001
    group: devops
    groups: 
      - sudo
      - devops
    state: present
    
- name: install other basic packages
  apt: 
    pkg:
      - tree
      - curl
      - htop 
      - sudo
      - git
      - zip
      - unzip

- name: Fetch current user information
  shell: whoami
  changed_when: false
  register: whoami

- name: Print current user information
  debug:
    var: whoami.stdout