---
# tasks file for common
- name: create devops group
  become: yes
  become_user: root
  group:
    name: devops
    state: present

- name: Allow 'devops' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%devops'
    line: '%devops ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: create devops user with admin privileges and assign to devops group
  become: yes
  become_user: root
  user: 
    name: "devops"
    password: "{{devops_default_password | password_hash('sha512')}}"
    comment: "DevOps User"
    uid: 2001
    shell: /bin/bash
    groups: 
      - sudo
      - devops
      - vagrant
    append: yes
    state: present
    
- name: install other basic packages
  apt: 
    pkg:
      - tree
      - curl
      - htop 
      - sudo
      - git
      - zip
      - unzip
      - expect

# - name: Fetch current user information
#   shell: whoami
#   changed_when: false
#   register: whoami

# - name: Print current user information
#   debug:
#     var: whoami.stdout