---
# tasks file for common
- name: create devops group
  become: yes
  become_user: root
  group:
    name: devops
    state: present
    
- name: create devops user with admin privileges and assign to devops group
  become: yes
  become_user: root
  user: 
    name: "devops"
    password: "devops"
    comment: "DevOps User"
    uid: 2001
    group: devops
    groups: 
      - sudo
      - devops
    state: present
    
- name: install other basic packages
  apt: 
    pkg:
      - tree
      - curl
      - htop 
      - sudo
      - git
      - zip
      - unzip

- name: Make ngrok Directory
  file:
    path: "/usr/lib/ngrok"
    state: directory

- name: Download ngrok 
  get_url:
    url: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
    dest: /etc/ngrok.zip
    mode: 0644

- name: unzip ngrok ZIP file
  unarchive:
    src: /etc/ngrok.zip
    dest: /usr/lib/ngrok
    remote_src: yes

# - name: set ngrok PATH in /etc/environment
#   lineinfile:
# #    path: /home/vagrant/.profile
#     path: /etc/environment
#     state: present
#     line: "{{ item }}"
#   with_items:
#   - 'export PATH=$PATH:/usr/lib/ngrok/ngrok'

# - name: source /etc/environment
#   become: yes
#   shell: source /etc/environment
#   args: 
#     executable: /bin/sh

- name: Assign ngrok account auth token
  shell: "/usr/lib/ngrok/ngrok authtoken 1qsCUjLBDm8Sy5s6xpy8p4gKpa6_4a4GM638mPiVNaCe2hqms"
  register: ngrok_auth_token

- name: Print ngrok auth token assignment result
  debug:
    var: ngrok_auth_token

# - name: Start ngrok 
#   shell: /usr/lib/ngrok/ngrok http 8080
#   register: ngrok_start_result

# - name: Print ngrok Start Result
#   debug:
#     var: ngrok_start_result

# - name: Install & setup sdkman and JDK 8
#   script: ../files/sdkman-jdk-setup.sh

