---
- name: Update APT packages
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Import Jenkins Key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Add Jenkins Repository to /etc/apt/sources.list
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    update_cache: true
    state: present

# - name: Change Jenkins JAVA options to skip the setup wizard
#   lineinfile:
#     dest: /etc/init.d/jenkins
#     regexp: ^JENKINS_JAVA_OPTIONS=
#     line: JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"

- name: Ensure Jenkins is running
  service:
    name: jenkins
    state: started 
    

# - name: Sleep for 30 seconds 
#   wait_for: 
#     timeout: 30

- name: Init Jenkins password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: jenkinsPasswrd

- name: Print Jenkins Password
  debug: 
    var: jenkinsPasswrd.stdout
