---
JDK_VERSION: 11.0.2
JDK_URL: https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
JDK_SHA256_CHECKSUM: 99be79935354f5c0df1ad293620ea36d13f48ec3ea870c838f20c504c9668b57
JDK_URL_DEST_FILE: /etc/open-jdk11.tar.gz
JDK_EXTRACT_DIR: /usr/lib/java11
JDK_HOME_DIR: /usr/lib/java11/jdk-11.0.2 
JDK_ALTERNATIVES_FULL_PATH: /usr/lib/java11/jdk-11.0.2/bin/java

# JDK_VERSION: 9
# JDK_URL: https://download.java.net/java/GA/jdk9/9/binaries/openjdk-9_linux-x64_bin.tar.gz
# JDK_SHA256_CHECKSUM: f908e31b6185e11b322825809172dcbb7ac0dce64061c9cf154cb1b0df884480
# JDK_URL_DEST_FILE: /etc/open-jdk9.tar.gz
# JDK_EXTRACT_DIR: /usr/lib/java9
# JDK_HOME_DIR: /usr/lib/java9/jdk-9
# JDK_ALTERNATIVES_FULL_PATH: /usr/lib/java9/jdk-9/bin/java

# JDK_VERSION: 15.0.2
# JDK_URL: https://download.java.net/java/GA/jdk15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_linux-x64_bin.tar.gz
# JDK_SHA256_CHECKSUM: 91ac6fc353b6bf39d995572b700e37a20e119a87034eeb939a6f24356fbcd207
# JDK_URL_DEST_FILE: /etc/open-jdk15.tar.gz
# JDK_EXTRACT_DIR: /usr/lib/java15
# JDK_HOME_DIR: /usr/lib/java15/jdk-15.0.2
# JDK_ALTERNATIVES_FULL_PATH: /usr/lib/java15/jdk-15.0.2/bin/java