- hosts: tools
  strategy: debug
  user: vagrant
  become: yes
  become_method: sudo
  become_user: root
  roles: 
  # - docker-debian
   - openJDK
  # - oracleJDK
   - gradle
   - jenkins
  # - docker-jenkins
  # - docker-nginx
   - ngrok
  