---
# Install Open JDK 8
- name: Install public key from JFrog openJDK
  apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    state: present

- name: Add JFrog openJDK repository
  apt_repository:
    repo: 'deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main'
    update_cache: yes
    state: present

- name: Install JFrog open JDK 8
  apt:
    name: adoptopenjdk-8-hotspot
    update_cache: true
    state: present

- name: set JAVA_HOME in /etc/profile
  lineinfile:
    path: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
  - 'JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64'
  - 'PATH=$PATH:$JAVA_HOME/bin'

- name: Check JAVA_HOME
  command: "echo $JAVA_HOME"
  register: java_home

- name: Print JAVA_HOME
  debug: 
    var: java_home.stdout
