- name: Get Open JDK TAR ball
  become: yes
  get_url:
    url: https://download.java.net/java/GA/jdk15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_linux-x64_bin.tar.gz
    dest: /etc/open-jdk15.tar.gz
    checksum: sha256:91ac6fc353b6bf39d995572b700e37a20e119a87034eeb939a6f24356fbcd207
    validate_certs: false
    mode: 0644
    
- name: Make JAVA 15 Directory
  file:
    path: /usr/lib/java15
    state: directory

- name: Unpack TAR ball
  unarchive:
    dest: /usr/lib/java15
    src: /etc/open-jdk15.tar.gz
    remote_src: yes

- name: Update Alternatives for JAVA
  alternatives:
    name: java
    path: /usr/lib/java15/jdk-15.0.2/bin/java
    link: /usr/bin/java
    priority: 20000

- name: set JAVA_HOME
  shell: "echo $JAVA_HOME"
  environment:
    JAVA_HOME: /usr/lib/java15/jdk-15.0.2
  register: java_home

- name: Print JAVA_HOME
  debug: 
    var: java_home.stdout

- name: set JAVA_HOME in .profile
  insertafter: EOF
  lineinfile:
    path: /home/vagrant/.profile
    state: present
    line: "{{ item }}"
  with_items:
  - 'export JAVA_HOME=/usr/lib/java15/jdk-15.0.2'
  - 'export PATH=$PATH:$JAVA_HOME/bin'
