---
# Open JDK 11 Installation
- name: Install Open JDK 11
  apt:
    name: openjdk-11-jdk
    update_cache: true
    state: present

- name: set JAVA_HOME in /etc/profile
  lineinfile:
    path: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
  - 'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
  - 'PATH=$PATH:$JAVA_HOME/bin'

- name: Check JAVA_HOME
  command: "echo $JAVA_HOME"
  register: java_home

- name: Print JAVA_HOME
  debug: 
    var: java_home.stdout
