---
# Open JDK 11 Installation
- name: Install Open JDK 11
  apt:
    name: openjdk-11-jdk
    update_cache: true
    state: present

- name: set JAVA_HOME in /etc/environment
  lineinfile:
#    path: /home/vagrant/.profile
    path: /etc/environment
    state: present
    line: "{{ item }}"
  with_items:
  - 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
  - 'export PATH=$PATH:$JAVA_HOME/bin'

- name: source /etc/environment
  shell: source /etc/environment
  args: 
    executable: /bin/bash