---
- name: Download Gradle 
  become: yes
  get_url:
    url: https://services.gradle.org/distributions/gradle-6.8.3-bin.zip
    dest: /etc/gradle-6.8.3-bin.zip
    mode: 0644

- name: Make Gradle Directory
  file:
    path: /usr/lib/gradle
    state: directory

- name: Unpack TAR ball
  unarchive:
    dest: /usr/lib/gradle
    src: /etc/gradle-6.8.3-bin.zip
    remote_src: yes

- name: Set GRADLE_HOME Environment variable
  blockinfile:
    insertafter: EOF
    path: /etc/environment
    block: export PATH=$PATH:/usr/lib/gradle/bin
