---
- include_vars: ../vars/main.yml

- name: Download Gradle {{ GRADLE_VERSION }}
  get_url:
    url: "{{GRADLE_URL}}" 
    dest: "{{GRADLE_URL_DEST_FILE}}"
    mode: 0644

- name: Make Gradle Directory
  file:
    path: "{{GRADLE_EXTRACT_DIR}}"
    state: directory

- name: Unpack Gradle zip File
  unarchive:
    dest: "{{GRADLE_EXTRACT_DIR}}"
    src: "{{ GRADLE_URL_DEST_FILE }}"
    remote_src: yes

- name: set GRADLE_HOME in /etc/profile
  lineinfile:
    path: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
  - 'GRADLE_HOME={{GRADLE_HOME_DIR}}'
  - 'PATH=$PATH:$GRADLE_HOME/bin'

# - name: Check GRADLE_HOME
#   command: "echo $GRADLE_HOME"
#   register: gradle_home

# - name: Print GRADLE_HOME
#   debug: 
#     var: gradle_home.stdout

