---
- name: Download Gradle 
  become: yes
  get_url:
    url: https://services.gradle.org/distributions/gradle-6.8.3-bin.zip
    dest: /etc/gradle-6.8.3-bin.zip
    mode: 0644

- name: Make Gradle Directory
  file:
    path: /usr/lib/gradle
    state: directory

- name: Unpack Gradle zip File
  unarchive:
    dest: /usr/lib/gradle
    src: /etc/gradle-6.8.3-bin.zip
    remote_src: yes

- name: set GRADLE_HOME
  shell: "echo $GRADLE_HOME"
  environment:
    GRADLE_HOME: /usr/lib/gradle/gradle-6.8.3
  register: gradle_home

- name: Print GRADLE_HOME
  debug: 
    var: gradle_home.stdout

- name: set GRADLE_HOME in .profile
  lineinfile:
    path: /home/vagrant/.profile
    state: present
    line: "{{ item }}"
  with_items:
  - 'export GRADLE_HOME=/usr/lib/gradle/gradle-6.8.3'
  - 'export PATH=$PATH:$GRADLE_HOME/bin'

- name: source .profile file in the shell
  become: no
  shell: source /home/vagrant/.profile
  args: 
    executable: /bin/bash