---
- include_vars: ../vars/main.yml

- name: Download Gradle {{ GRADLE_VERSION }}
  get_url:
    url: "{{GRADLE_URL}}" 
    dest: "{{GRADLE_URL_DEST_FILE}}"
    mode: 0644

- name: Make Gradle Directory
  file:
    path: "{{GRADLE_EXTRACT_DIR}}"
    state: directory

- name: Unpack Gradle zip File
  unarchive:
    dest: "{{GRADLE_EXTRACT_DIR}}"
    src: "{{ GRADLE_URL_DEST_FILE }}"
    remote_src: yes

- name: set GRADLE_HOME
  shell: "echo $GRADLE_HOME"
  environment:
    GRADLE_HOME: "{{GRADLE_HOME_DIR}}"
  register: gradle_home

- name: Print GRADLE_HOME
  debug: 
    var: gradle_home.stdout

- name: set GRADLE_HOME in /etc/environment
  lineinfile:
    path: /etc/environment
    state: present
    line: "{{ item }}"
  with_items:
  - 'export GRADLE_HOME={{GRADLE_HOME_DIR}}'
  - 'export PATH=$PATH:$GRADLE_HOME/bin'

- name: source /etc/environment
  shell: source /etc/environment
  args: 
    executable: /bin/bash