---
- name: Check if ngrok zip file exists
  stat: 
    path: /usr/local/etc/ngrok.zip
  register: ngrok_zip_file

- name: Download ngrok 
  get_url:
    url: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
    dest: /usr/local/etc/ngrok.zip
    mode: 0644
  when: not ngrok_zip_file.stat.exists

- name: Check if ngrok command file exists
  stat:
    path: /usr/local/bin/ngrok
  register: ngrok_file

- name: unzip ngrok ZIP file
  unarchive:
    src: /usr/local/etc/ngrok.zip
    dest: /usr/local/bin
    remote_src: yes
  when: not ngrok_file.stat.exists

- name: Assign ngrok account auth token
  command: "ngrok authtoken 1qsCUjLBDm8Sy5s6xpy8p4gKpa6_4a4GM638mPiVNaCe2hqms"
  register: ngrok_auth_token

- name: Print ngrok auth token assignment result
  debug:
    var: ngrok_auth_token

- name: Copy ngrok shell script
  copy: 
    src: start-ngrok.sh 
    dest: ~/ 
    mode: 0777

- name: Start ngrok
  command: sh ~/start-ngrok.sh 8081
  register: ngrok_url

- name: Print ngrok Jenkins URL
  debug:
    var: ngrok_url
